- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: remove nginx default page
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: download source code and unarchive
  ansible.builtin.unarchive:
    src:  https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: /usr/share/nginx/html

- name: config reverse proxy 
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf

- name: start service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes